<a href="https://colab.research.google.com/github/ayeshashoaib-3000/data-science-bootcamp/blob/main/data_science_bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SESSION 3 CLASSWORK

In [19]:
import pandas as pd
import numpy as np
print("done")

done

In [20]:
from google.colab import files
uploaded = files.upload()

Saving Karachi_House_Price_Dataset.csv to Karachi_House_Price_Dataset (1).csv

In [21]:
df = pd.read_csv("Karachi_House_Price_Dataset.csv")

In [22]:
df.head()   # it shows actual values  not just schema

,Unnamed: 0,Address,Price,NoOfBedrooms,NoOfBathrooms,AreaSqYards,WebURL
0,0,"Bahria Town Karachi, Karachi",4200000.0,1.0,1.0,60,https://www.zameen.com/Homes/Karachi-2-1.html
1,1,"Bahria Town - Precinct 17, Bahria Town Karachi",5900000.0,2.0,2.0,161,https://www.zameen.com/Homes/Karachi-2-1.html
2,2,"Bahria Paradise, Bahria Town Karachi",42000000.0,5.0,5.0,500,https://www.zameen.com/Homes/Karachi-2-1.html
3,3,"Askari 5 - Sector J, Askari 5",37500000.0,3.0,3.0,300,https://www.zameen.com/Homes/Karachi-2-1.html
4,4,"Bahria Town - Precinct 35, Bahria Sports City",21000000.0,4.0,4.0,350,https://www.zameen.com/Homes/Karachi-2-1.html

In [23]:
df.head(4)    # shows first n rows

,Unnamed: 0,Address,Price,NoOfBedrooms,NoOfBathrooms,AreaSqYards,WebURL
0,0,"Bahria Town Karachi, Karachi",4200000.0,1.0,1.0,60,https://www.zameen.com/Homes/Karachi-2-1.html
1,1,"Bahria Town - Precinct 17, Bahria Town Karachi",5900000.0,2.0,2.0,161,https://www.zameen.com/Homes/Karachi-2-1.html
2,2,"Bahria Paradise, Bahria Town Karachi",42000000.0,5.0,5.0,500,https://www.zameen.com/Homes/Karachi-2-1.html
3,3,"Askari 5 - Sector J, Askari 5",37500000.0,3.0,3.0,300,https://www.zameen.com/Homes/Karachi-2-1.html

In [25]:
df.shape   #  shows rows ,columns and size

(19450, 7)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19450 entries, 0 to 19449
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     19450 non-null  int64
 1   Address        19450 non-null  object
 2   Price          19450 non-null  float64
 3   NoOfBedrooms   17391 non-null  float64
 4   NoOfBathrooms  19296 non-null  float64
 5   AreaSqYards    19450 non-null  int64
 6   WebURL         19450 non-null  object
dtypes: float64(3), int64(2), object(2)
memory usage: 1.0+ MB

In [28]:
df.describe()    #  shows count, median ,deviation,  meas  , standard, max& min for numeric columns

         Unnamed: 0         Price  NoOfBedrooms  NoOfBathrooms   AreaSqYards
count  19450.000000  1.945000e+04  17391.000000   19296.000000  19450.000000
mean    9724.500000  4.284362e+07      3.665977       3.392050    206.394807
std     5614.875704  5.104344e+07      1.518615       1.844473    151.815496
min        0.000000  7.000000e+05      1.000000       0.000000      0.000000
25%     4862.250000  1.350000e+07      3.000000       2.000000    106.000000
50%     9724.500000  2.500000e+07      3.000000       3.000000    178.000000
75%    14586.750000  5.980000e+07      5.000000       5.000000    300.000000
max    19449.000000  8.500000e+08     11.000000      10.000000    993.000000

In [30]:
df.columns.tolist()      # shows all the columns in pandas file

['Unnamed: 0',
 'Address',
 'Price',
 'NoOfBedrooms',
 'NoOfBathrooms',
 'AreaSqYards',
 'WebURL']

In [31]:
df.columns   # shows all the columns  , 'object' means it is in sentence form but  is not considered as string

Index(['Unnamed: 0', 'Address', 'Price', 'NoOfBedrooms', 'NoOfBathrooms',
       'AreaSqYards', 'WebURL'],
      dtype='object')

In [32]:
df.value_counts()  # it  simply asks how many times avalue occurs in target column

Unnamed: 0  Address                                         Price       NoOfBedrooms  NoOfBathrooms  AreaSqYards  WebURL
19449       Gwalior Cooperative Housing Society, Scheme 33  8000000.0   2.0           2.0            106          https://www.zameen.com/Homes/Karachi-2-778.html    1
0           Bahria Town Karachi, Karachi                    4200000.0   1.0           1.0            60           https://www.zameen.com/Homes/Karachi-2-1.html      1
1           Bahria Town - Precinct 17, Bahria Town Karachi  5900000.0   2.0           2.0            161          https://www.zameen.com/Homes/Karachi-2-1.html      1
2           Bahria Paradise, Bahria Town Karachi            42000000.0  5.0           5.0            500          https://www.zameen.com/Homes/Karachi-2-1.html      1
3           Askari 5 - Sector J, Askari 5                   37500000.0  3.0           3.0            300          https://www.zameen.com/Homes/Karachi-2-1.html      1
                                                                                                                                                                    ..
10          Askari 5 - Sector J, Askari 5                   64300000.0  5.0           5.0            375          https://www.zameen.com/Homes/Karachi-2-1.html      1
8           North Nazimabad - Block F, North Nazimabad      18000000.0  3.0           3.0            150          https://www.zameen.com/Homes/Karachi-2-1.html      1
7           Askari 5 - Sector J, Askari 5                   68000000.0  5.0           5.0            375          https://www.zameen.com/Homes/Karachi-2-1.html      1
6           Bahria Town - Precinct 1, Bahria Town Karachi   35000000.0  5.0           6.0            272          https://www.zameen.com/Homes/Karachi-2-1.html      1
5           Bahria Paradise, Bahria Town Karachi            46500000.0  5.0           5.0            500          https://www.zameen.com/Homes/Karachi-2-1.html      1
Name: count, Length: 17237, dtype: int64

In [34]:
df.isnull().sum()   # it tells the missing  value data type in integer

Unnamed: 0          0
Address             0
Price               0
NoOfBedrooms     2059
NoOfBathrooms     154
AreaSqYards         0
WebURL              0
dtype: int64